### ISSUE TITLE
Multi-Threading NOT working properly

### ISSUE THREAD

**Issue by FernandoRojasCesiCorp** [KiaArmani/WoWUE4CmdImport#2]
So, I noticed it has the AmountOfAssetsToProcess but all that does is omit the amount of files assigned to that value but it also passes them to the Imported folder which is a False Positive since they didn't import, also the last File on my Filename Array didn't import … I'm trying to see if I can fix all of this issues my self and send you a pull request, but if you know how to fix those issues or maybe have a local change to fix them please let me know

-Fernando

**Comment by KiaArmani** [comment]
I will have a look this weekend. Thanks for bringing this up! 




Outlook for Android herunterladen







On Thu, Dec 6, 2018 at 7:52 PM +0100, "FernandoRojasCesiCorp" <notifications@github.com> wrote:












So, I noticed it has the AmountOfAssetsToProcess but all that does is omit the amount of files assigned to that value but it also passes them to the Imported folder which is a False Positive since they didn't import, also the last File on my Filename Array didn't import … I'm trying to see if I can fix all of this issues my self and send you a pull request, but if you know how to fix those issues or maybe have a local change to fix them please let me know



-Fernando

**Comment by FernandoRojasCesiCorp** [comment]
thanks, Ill let you know if I find a solution, really powerful tool you made

**Comment by KiaArmani** [comment]
Should be resolved now. Closed.
